spring.application.name=dqchecker

# Database
spring.datasource.url=jdbc:postgresql://ep-misty-flower-aof4c6c4-pooler.c-2.ap-southeast-1.aws.neon.tech/neondb?sslmode=require
spring.datasource.username=neondb_owner
spring.datasource.password=npg_u3nX8fwlcdJT

spring.datasource.driver-class-name=org.postgresql.Driver

# JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Server
server.port=8080

# JWT
jwt.secret=${JWT_SECRET:mysecretkeymysecretkeymysecretkey1234567890}
jwt.expiration=${JWT_EXPIRATION:86400000}

# OpenAPI
springdoc.swagger-ui.path=/swagger-ui/index.html

# Actuator
management.endpoints.web.exposure.include=health,info
management.endpoint.health.show-details=always
management.info.env.enabled=true
info.app.name=DQ Checker
info.app.description=CSV data quality validation API
info.app.version=1.0.0
